### ISSUE TITLE
"name 'PUINT' is not defined" - pyglet installation by ratcave

### ISSUE THREAD

**Issue by mohammadbashiri** [nickdelgrosso/ratcave#23]
Hi Nick,
i tried intalling ratcave and psychopy. However when i installed ratcave and then psychopy, i got an error (as mentioned in the issue title). The problem was solved when i installed psychopy installation requirements and then installed ratcave at the end. So maybe there is some issue with the pyglet installation that ratcave does.

**Comment by nickdelgrosso** [comment]
Hi Mohammad,

This seems to be a pyglet version issue that they've identified (https://bitbucket.org/pyglet/pyglet/issues/170/nameerror-name-puint-is-not-defined)  and should be fixed soon.  To resolve it in the meantime, I've updated the installation instructions in the readme to a manual pyglet installation.
